"""Live 5CA tracker: one internal page covering every campaign area.

    python3 tools/make_5ca_tracker.py [week-commencing]

Writes docs/5ca-tracker.html. Regenerated by the Monday run so the placements
the team works from are never staler than a week, instead of living as dated
CSVs nobody opens.

Per area: the gradient shape, the change since last week, and the target list
(members with no recorded position, with abstentionist and devolved-seat
members separated out rather than presented as persuadable). Decisive columns
expand to full member lists; the bulk of the 0 column does not, since 600
rows of "no evidence" is noise.

INTERNAL ONLY. Stance placements are CitizenGO's own analysis of named
parliamentarians, not public record, so this page must never be served from
the partner site's passphrase, which allies hold.
"""

from __future__ import annotations

import datetime
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from src import db, intel, stance

ABSTENTIONIST = ("Sinn F", "Speaker")
DEVOLVED = ("Scottish National Party", "Social Democratic & Labour Party",
            "Democratic Unionist Party", "Traditional Unionist Voice",
            "Alliance", "Ulster Unionist Party", "Plaid Cymru")

COLUMN_LABEL = {"++": "Strong ally", "+": "Leans our way", "0": "No position",
                "-": "Leans against", "--": "Strong opponent"}

PAGE = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>5CA tracker (internal)</title>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
<style>
body {{ font: 15px/1.55 Roboto, sans-serif; color:#52575C; max-width:70rem;
       margin:0 auto; padding:1rem 1.5rem 3rem; }}
h1 {{ color:#52575C; font-size:1.4rem; border-bottom:4px solid #4285f4; padding-bottom:.4rem; }}
.internal {{ background:#FFEBAD; border-left:4px solid #DB544F; padding:.6rem 1rem;
            font-size:.88em; border-radius:0 4px 4px 0; }}
.stats {{ display:flex; gap:.8rem; flex-wrap:wrap; margin:1.1rem 0 1.6rem; }}
.stat {{ border:1px solid #EEEEEE; border-radius:6px; padding:.55rem 1rem; text-align:center; }}
.stat b {{ display:block; font-size:1.35em; color:#4285f4; }}
.stat span {{ font-size:.78em; }}
.area {{ border:1px solid #EEEEEE; border-radius:8px; padding:1rem 1.2rem; margin:1rem 0; }}
.area h2 {{ color:#4285f4; font-size:1.05rem; margin:0 0 .1rem; }}
.evidence {{ font-size:.82em; opacity:.8; margin:0 0 .7rem; }}
.bar {{ display:flex; height:1.5rem; border-radius:4px; overflow:hidden; margin:.5rem 0 .3rem; }}
.seg {{ font-size:.7em; color:#FFF; display:flex; align-items:center;
       justify-content:center; font-weight:700; }}
.seg.pp {{ background:#55B159; }} .seg.p {{ background:#9ccf9e; color:#2f4030; }}
.seg.z {{ background:#EEEEEE; color:#52575C; }}
.seg.m {{ background:#e9a09d; color:#4a2523; }} .seg.mm {{ background:#DB544F; }}
.legend {{ font-size:.76em; display:flex; gap:.9rem; flex-wrap:wrap; margin:.2rem 0 .6rem; }}
.legend i {{ width:.7em; height:.7em; border-radius:2px; display:inline-block; margin-right:.25em; }}
.delta {{ font-size:.8em; margin:.4rem 0; }}
.delta b {{ color:#4285f4; }}
.up {{ color:#55B159; font-weight:700; }} .down {{ color:#DB544F; font-weight:700; }}
details {{ border-left:3px solid #EEEEEE; padding-left:.8rem; margin:.5rem 0; }}
summary {{ cursor:pointer; font-size:.86em; font-weight:700; color:#4285f4; }}
ul {{ padding-left:1.1rem; margin:.35rem 0; font-size:.84em; }}
li {{ margin:.16rem 0; }}
.aside {{ font-size:.8em; opacity:.8; margin:.35rem 0; }}
.foot {{ font-size:.8em; opacity:.7; border-top:1px solid #EEEEEE;
        margin-top:2rem; padding-top:.8rem; }}
</style></head><body>
<h1>5CA tracker <span style="font-weight:400;font-size:.68em">week commencing {week}</span></h1>
<p class="internal"><strong>Internal only.</strong> These are CitizenGO's own stance
placements for named parliamentarians, derived from the evidence ledger. They are
suggestions for a campaigner to confirm, not published positions, and they must not
be shared outside the organisation or served from the partner site.</p>

<div class="stats">
<div class="stat"><b>{events:,}</b><span>ledger events</span></div>
<div class="stat"><b>{members:,}</b><span>parliamentarians</span></div>
<div class="stat"><b>{scored:,}</b><span>scored evidence refs</span></div>
<div class="stat"><b>{areas}</b><span>campaign areas</span></div>
<div class="stat"><b>{earliest} to {latest}</b><span>evidence window</span></div>
</div>

<p class="legend">
<span><i style="background:#55B159"></i>++ strong ally</span>
<span><i style="background:#9ccf9e"></i>+ leans our way</span>
<span><i style="background:#EEEEEE"></i>0 no position</span>
<span><i style="background:#e9a09d"></i>- leans against</span>
<span><i style="background:#DB544F"></i>-- strong opponent</span>
</p>

{areas_html}

<p class="foot">Generated {stamp} from the parliamentary monitor's evidence ledger.
Placements use the strongest evidence per member (a recorded vote outranks a speech,
a speech a motion, a motion a question; free votes outrank whipped ones), with
CitizenGO's editorial rules in config/stance_overrides.yaml applied on top.
Full 649-row sheets per area: <code>data/5ca/</code> in the monitor repo.</p>
</body></html>
"""


def party_of(name):
    m = re.search(r"\(([^,]+),", name)
    return m.group(1) if m else ""


def bar(counts, total):
    segs = []
    for key, cls in (("++", "pp"), ("+", "p"), ("0", "z"), ("-", "m"), ("--", "mm")):
        n = counts.get(key, 0)
        if not n:
            continue
        pct = 100.0 * n / total
        label = str(n) if pct >= 6 else ""
        segs.append('<div class="seg {0}" style="width:{1:.2f}%" title="{2}: {3}">{4}</div>'
                    .format(cls, pct, COLUMN_LABEL[key], n, label))
    return '<div class="bar">' + "".join(segs) + "</div>"


def delta_line(counts, prior):
    if not prior:
        return '<p class="delta">First edition on the tracker: this week is the baseline.</p>'
    bits = []
    for key in ("++", "+", "0", "-", "--"):
        change = counts.get(key, 0) - prior.get(key, 0)
        if change:
            cls = "up" if (change > 0) == (key in ("++", "+")) else "down"
            bits.append('{0} <span class="{1}">{2:+d}</span>'.format(key, cls, change))
    if not bits:
        return '<p class="delta">No change since last week.</p>'
    return '<p class="delta"><b>Since last week:</b> ' + " · ".join(bits) + "</p>"


def member_list(rows, limit=None):
    shown = rows[:limit] if limit else rows
    items = "".join("<li>{0}</li>".format(html.escape(r["decision_maker"])) for r in shown)
    if limit and len(rows) > limit:
        items += "<li><em>and {0} more</em></li>".format(len(rows) - limit)
    return "<ul>" + (items or "<li><em>none</em></li>") + "</ul>"


def main():
    week = sys.argv[1] if len(sys.argv) > 1 else (
        datetime.date.today() - datetime.timedelta(days=datetime.date.today().weekday())
    ).isoformat()
    conn = db.init_db(db.connect(os.path.join(ROOT, "data", "parl-monitor.db")))
    cfg = stance.load_overrides(os.path.join(ROOT, "config", "stance_overrides.yaml"))
    names = intel.area_names(os.path.join(ROOT, "config", "taxonomy.yaml"))
    excluded = cfg.get("excluded_from_5ca") or []
    ledger = intel.ledger_stats(conn)
    scored = conn.execute("SELECT COUNT(*) FROM stance").fetchone()[0]

    blocks = []
    tracked = 0
    for area in sorted(names):
        if area in excluded:
            continue
        rows = stance.suggest_rows(conn, area, full_roster=True, overrides_cfg=cfg)
        if not rows:
            continue
        tracked += 1
        counts = {}
        by_col = {}
        for r in rows:
            counts[r["column"]] = counts.get(r["column"], 0) + 1
            by_col.setdefault(r["column"], []).append(r)
        with_evidence = sum(1 for r in rows if r["n_events"])
        prior = stance.previous_snapshot(conn, area, week)
        stance.record_snapshot(conn, area, week, counts)

        zeros = by_col.get("0", [])
        non_voting = [r for r in zeros
                      if any(a in party_of(r["decision_maker"]) for a in ABSTENTIONIST)]
        devolved = [r for r in zeros if r not in non_voting
                    and party_of(r["decision_maker"]) in DEVOLVED]
        targets = [r for r in zeros if r not in non_voting and r not in devolved]
        conflicts = [r for r in rows if r["conflict"]]

        block = ['<div class="area"><h2>{0}</h2>'.format(html.escape(names[area])),
                 '<p class="evidence">{0} of {1} sitting MPs carry evidence on this area'
                 '{2}</p>'.format(with_evidence, len(rows),
                                  "; {0} with conflicting evidence".format(len(conflicts))
                                  if conflicts else ""),
                 bar(counts, len(rows)), delta_line(counts, prior)]
        for key in ("++", "+", "-", "--"):
            group = by_col.get(key, [])
            if group:
                block.append("<details><summary>{0} {1} ({2})</summary>{3}</details>".format(
                    key, COLUMN_LABEL[key], len(group), member_list(group, limit=60)))
        block.append("<details><summary>Target list: no position on record ({0})</summary>"
                     "{1}</details>".format(len(targets), member_list(targets, limit=60)))
        if non_voting or devolved:
            block.append('<p class="aside">Set aside as not persuadable: {0} abstentionist '
                         'or non-voting, {1} devolved-seat members who commonly abstain on '
                         'England-and-Wales bills.</p>'.format(len(non_voting), len(devolved)))
        block.append("</div>")
        blocks.append("\n".join(block))

    out = os.path.join(ROOT, "docs", "5ca-tracker.html")
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(PAGE.format(
            week=week, events=ledger["events"], members=ledger["members"],
            scored=scored, areas=tracked, earliest=ledger["earliest"],
            latest=ledger["latest"], areas_html="\n".join(blocks),
            stamp=datetime.date.today().isoformat()))
    conn.close()
    print("{0} ({1} areas)".format(out, tracked))


if __name__ == "__main__":
    main()
